theme: jekyll-theme-time-machine
permalink: :title/
baseurl: /Winnie_Blog
  _config.yml
  index.html
  _post
    2019-06-29-hello-world.html
    _Java8-new-feature
      2019-06-30-java8-lambda-standard-function-interface.md
